<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mad</string>
	</array>
	<key>name</key>
	<string>MADX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#madxComments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#madxVariables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#madxStrings</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([A-Za-z][A-Za-z0-9\._]{1,15}(\w*)\s*(\:)(?!\=))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Command Given by</string>
			<key>end</key>
			<string>(\;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.terminator</string>
				</dict>
			</dict>
			<key>name</key>
			<string>command</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#madxCommand</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#madxCommand</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\b(match)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.madx.matching</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Matching Mode</string>
			<key>end</key>
			<string>(?i)\b(endmatch)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.madx.matching</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#madxOperators</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>madxCommand</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\b(ECOLLIMATOR)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|XSIZE|YSIZE)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(BEAMBEAM)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(CHARGE|XMA|YMA|SIGX|SIGY|WIDTH|BBSHAPE|BBDIR)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(USE)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(SEQUENCE|PERIOD|RANGE|SURVEY)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(OPTION)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(FLAG)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(TKICKER)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|KICK|TILT|HKICK|VKICK)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(HKICKER)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|KICK|TILT)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(CRABCAVITY)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|VOLT|LAG|FREQ|HARMON|RV1|RV2|RV3|RV4|RPH1|RPH2|LAGF)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(NLLENS)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(KNLL|CNLL)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(SEXTUPOLE)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|K2|K2S|TILT)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(RBEND)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|ANGLE|TILT|K0|K1|K2|E1|E2|FINT|FINTX|HGAP|H1|H2|THICK)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(BEAM)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(PARTICLE|MASS|CHARGE|ENERGY|PARTICLEGAMMA|BETA|BRHO|EX|EXN|EY|EYN|EY|SIGT|SIGE|KBUNCH|NPART|BCURRENT|BUNCHED|RADIATE|BV|SEQUENCE)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(COLLIMATOR)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|APERTYPE|APERTURE|APER_OFFSET|APER_TOL)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(VMONITOR)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(KICKER)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|KICK|TILT|HKICK|VKICK)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(QUADRUPOLE)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|K1|K1S|TILT|THICK)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(HMONITOR)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(RFMULTIPOLE)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|VOLT|LAG|FREQ|HARMON|LRAD|TILT|KNL|KSL|PNL|PSL)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(RESBEAM)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(SEQUENCE)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(SELECT)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(FLAG|RANGE|CLASS|PATTERN|SEQUENCE|FULL|CLEAR|COLUMN|SLICE|THICK)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(MONITOR)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(OCTUPOLE)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|K3|K3S|TILT)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(SET)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(FORMAT|SEQUENCE)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(MATRIX)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(TYPE|L|KICK1|KICK6|RM11|RM66|TM111|TM666)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(MULTIPOLE)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(LRAD|TILT|KNL|KSL)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(RCOLLIMATOR)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|XSIZE|YSIZE)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(DIPEDGE)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(H|E1|FINT|HGAP|TILT)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(DRIFT)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(YROTATION)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(ANGLE)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(CHANGEREF)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(PATCH_ANG|PATCH_TRANS)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(SROTATION)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(ANGLE)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(INSTRUMENT)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(RFCAVITY)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|VOLT|LAG|FREQ|HARMON|N_BESSEL|NO_CAVITY_TOTALPATH)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(SBEND)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|ANGLE|TILT|K0|K1|K2|E1|E2|FINT|FINTX|HGAP|H1|H2|THICK)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(TRANSLATION)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(X|Y|T|PX|PY|PT)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(ELSEPARATOR)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|EX|EY|TILT)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(PLACEHOLDER)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(SOLENOID)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|KS|KSI)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(VKICKER)(\s*)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.attribute.cattribute</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Attributes</string>
							<key>match</key>
							<string>(?i)\b(L|KICK|TILT)(\s*)((\=)|\:\=)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxComments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madxOperators</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#madxComments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#madxOperators</string>
				</dict>
			</array>
		</dict>
		<key>madxComments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\!</string>
					<key>comment</key>
					<string>Single Line Comment</string>
					<key>contentName</key>
					<string>comment.line</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\/\*</string>
					<key>comment</key>
					<string>Block Comment - match is a pair of /* */</string>
					<key>end</key>
					<string>\*\/</string>
					<key>name</key>
					<string>comment.block</string>
				</dict>
			</array>
		</dict>
		<key>madxOperators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((\:\=)|(\=)|(\-\&gt;)|(\+)|(\-)|(\/)|(\&lt;)|(\&gt;))</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\;)</string>
					<key>name</key>
					<string>keyword.operator.terminator</string>
				</dict>
			</array>
		</dict>
		<key>madxString</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\')|(\")</string>
					<key>comment</key>
					<string>Strings</string>
					<key>end</key>
					<string>(\')|(\")</string>
					<key>name</key>
					<string>string</string>
				</dict>
			</array>
		</dict>
		<key>madxVariables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\#(S|E)\b</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(x|px|y|py|t|pt|deltap|s|TRUE|FALSE)\b</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(xn|pxn|wx|phix|yn|pyn|wy|phiy|tn|ptn|wt|phit)\b</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b((bet|alf|mu|d|dp|)(x|y))\b</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(r11|r12|r21|r22)\b</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.madx</string>
	<key>uuid</key>
	<string>b57b29bd-8a7c-4ca9-9346-6a5dc8cc5bd6</string>
</dict>
</plist>
