<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mad</string>
	</array>
	<key>name</key>
	<string>MADX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#madxComments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#madxVariables</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\')|(\")</string>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>(\')|(\")</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([A-Za-z][A-Za-z0-9\._]{1,15}(\w*)\s*(\:)(?!\=))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>label</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Command Given by</string>
			<key>end</key>
			<string>(\;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.terminator</string>
				</dict>
			</dict>
			<key>name</key>
			<string>command</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#madxCommand</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#madxCommand</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>madxCommand</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(EXIT|QUIT|STOP|HELP|SHOW|VALUE|OPTION|EXEC|SET|SYSTEM|TITLE|USE|SELECT)\b</string>
					<key>name</key>
					<string>keyword.operator.madx.generalControl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(ASSIGN|CALL(S{0,1})|RETURN|PRINT|PRINTF|RENAMEFILE|COPYFILE|REMOVEFILE)</string>
					<key>name</key>
					<string>keyword.operator.madx.fileHandling</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(CREATE|DELETE|READTABLE|READMYTABLE|WRITE|SETVARS|SETVARS_LIN|FILL|SHRINK)\b</string>
					<key>name</key>
					<string>keyword.operator.madx.fileHandling</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(BEAM|RESBEAM)\b</string>
					<key>name</key>
					<string>keyword.operator.madx.beam</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(SEQEDIT|FLATTEN|CYCLE|REFLECT|INSTALL|MOVE|REMOVE|REPLACE|EXTRACT|ENDEDIT|SAVE|DUMPSEQU)\b</string>
					<key>name</key>
					<string>keyword.operator.madx.sequenceEditor</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(RANGE|CLASS)\b</string>
					<key>name</key>
					<string>keyword.operator.madx.rangeAndClass</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(PLOT|SETPLOT|RESPLOT|RPLOT)\b</string>
					<key>name</key>
					<string>keyword.operator.madx.rangeAndClass</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(hkicker|vkicker|tkicker|kicker)\b</string>
					<key>name</key>
					<string>keyword.operator.madx.element</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\b(match)\b(\s*)(\,)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx.matching</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Matching Mode.</string>
					<key>end</key>
					<string>(?i)\b(endmatch)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.madx.matching</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#matchingMode</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(marker|drift|line|sbend|rbend|dipedge|quadrupole|sextupole|octupole|multipole|solenoid|nllens|rfcavity|rfmultipole|crabcavity|elseparator)\b</string>
					<key>name</key>
					<string>keyword.operator.madx.element</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(hmonitor|vmonitor|monitor|instrument|placeholder|collimator|beambeam|matrix|yrotation|srotation|translation|changeref)(?=\b)</string>
					<key>name</key>
					<string>keyword.operator.madx.element</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(twiss)(?=\b)</string>
					<key>name</key>
					<string>keyword.operator.madx.twiss</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)(eprint|esave|ealign|eoption|efcomp|seterr)(?=\b)</string>
					<key>name</key>
					<string>keyword.operator.madx.errorDef</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#madxComments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#madxOperators</string>
				</dict>
			</array>
		</dict>
		<key>madxComments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Comment - match is a pair of /* */</string>
					<key>match</key>
					<string>(\!)(\*){10,}</string>
					<key>name</key>
					<string>comment.separator</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\!</string>
					<key>comment</key>
					<string>Comment</string>
					<key>contentName</key>
					<string>comment.line</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\/\*</string>
					<key>comment</key>
					<string>Comment - match is a pair of /* */</string>
					<key>end</key>
					<string>\*\/</string>
					<key>name</key>
					<string>comment.block</string>
				</dict>
			</array>
		</dict>
		<key>madxOperators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\:\=)|(\=)|(\-\&gt;)|(\;)|(\+)|(\-)|(\/)|(\&lt;)|(\&gt;)</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\;)</string>
					<key>name</key>
					<string>keyword.operator.terminator</string>
				</dict>
			</array>
		</dict>
		<key>madxVariables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\#(S|E)\b</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(x|px|y|py|t|pt|deltap|s|TRUE|FALSE)\b</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(xn|pxn|wx|phix|yn|pyn|wy|phiy|tn|ptn|wt|phit)\b</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b((bet|alf|mu|d|dp|)(x|y))\b</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(r11|r12|r21|r22)\b</string>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</array>
		</dict>
		<key>matchingMode</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(sequence|vary|constraint|weight|global|gweight|lmdif|migrad|simplex|jacobian)\b</string>
					<key>name</key>
					<string>keyword.operator.madx.matchingMode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#madxComments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#madxOperators</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.madx</string>
	<key>uuid</key>
	<string>b57b29bd-8a7c-4ca9-9346-6a5dc8cc5bd6</string>
</dict>
</plist>
